# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78cba44edb7ff8f290f5199e9beaf29fa7ff91ba2bb00c37a12858a5f9132102635bf92b31e1c8aecde786eaa1039df2bcb01519748e9127a0c3b75b554b6f66

test:
  secret_key_base: 575326ea4be8b5b23d6b2c7db802ec5d08880c9ae1fbe0af13426f027c6b073a8a647d48170ecbfa5ccc206cb9d60d71fee5e89036fedaebf86d9ccef72ea4e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
